[project]
name = "marl-incentives"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "GermÃ¡n Pardo-GonzÃ¡lez", email = "germanrpardo1@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "notebook>=7.4.3",
    "numpy>=2.2.6",
    "sumolib>=1.23.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
